# Generated by Django 5.2.3 on 2025-07-01 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('formFactor', models.CharField(max_length=100)),
                ('moboFormFactors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('supportedSockets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('isLiquid', models.BooleanField()),
                ('size', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('generation', models.PositiveIntegerField()),
                ('socket', models.CharField(max_length=100)),
                ('architecture', models.CharField(max_length=100)),
                ('coreCount', models.PositiveIntegerField()),
                ('threadCount', models.PositiveIntegerField()),
                ('boostClock', models.PositiveIntegerField()),
                ('TDP', models.PositiveIntegerField()),
                ('cacheSize', models.PositiveIntegerField()),
                ('coolerIncluded', models.BooleanField()),
                ('integratedGPU', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('boostClock', models.PositiveIntegerField()),
                ('VRAM', models.PositiveIntegerField()),
                ('TDP', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('socket', models.CharField(max_length=100)),
                ('formFactor', models.CharField(max_length=100)),
                ('chipset', models.CharField(max_length=100)),
                ('memoryType', models.CharField(max_length=100)),
                ('memorySlots', models.PositiveIntegerField()),
                ('memorySpeed', models.PositiveIntegerField()),
                ('mDotTwoSlots', models.PositiveIntegerField()),
                ('sataSlots', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('formFactor', models.CharField(max_length=100)),
                ('isModular', models.BooleanField()),
                ('wattage', models.PositiveIntegerField()),
                ('efficiency', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('speed', models.PositiveIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
    ]
