# Generated by Django 5.2.3 on 2025-08-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_rename_tdp_cpu_tdp_rename_tdp_gpu_tdp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcPartPickerId', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('isSSD', models.BooleanField()),
                ('formFactor', models.CharField(max_length=100)),
                ('cacheSize', models.PositiveIntegerField()),
                ('isNVMe', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='amount',
            new_name='size',
        ),
        migrations.AddField(
            model_name='case',
            name='threePointFiveDriveBays',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='twoPointFiveDriveBays',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StoragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(blank=True, max_length=500, null=True)),
                ('StorageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.storage')),
            ],
        ),
    ]
