# Generated by Django 5.2.3 on 2025-07-31 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_alter_cpu_pcpartpickerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='buyLink',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='price',
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcPartPickerId',
            field=models.CharField(default='car', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='GPUPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('available', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(blank=True, max_length=500, null=True)),
                ('GPUId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.gpu')),
            ],
        ),
    ]
