# Generated by Django 5.2.3 on 2025-08-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_coolerprice_alter_cooler_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAMPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='cooler',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ram',
            constraint=models.UniqueConstraint(fields=('name', 'size'), name='unique_ram_name_size'),
        ),
        migrations.AddField(
            model_name='ramprice',
            name='RAMId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.ram'),
        ),
        migrations.AddConstraint(
            model_name='ramprice',
            constraint=models.UniqueConstraint(fields=('RAMId', 'country'), name='unique_ram_country_price'),
        ),
    ]
