# Generated by Django 5.2.3 on 2025-08-11 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_alter_cooler_width_alter_cpuprice_buylink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='cooler',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cooler',
            constraint=models.UniqueConstraint(fields=('name', 'height', 'width'), name='unique_cooler_name_height_width'),
        ),
        migrations.AddField(
            model_name='coolerprice',
            name='CoolerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.cooler'),
        ),
        migrations.AddConstraint(
            model_name='coolerprice',
            constraint=models.UniqueConstraint(fields=('CoolerId', 'country'), name='unique_cooler_country_price'),
        ),
    ]
