# Generated by Django 5.2.3 on 2025-08-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_rename_depth_case_length_case_includedpsuwattage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
