# Generated by Django 5.2.3 on 2025-09-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_alter_ram_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='expansionSlotsViaRiser',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
