# Generated by Django 5.2.3 on 2025-09-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_case_expansionslotsviariser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='psu',
            constraint=models.UniqueConstraint(fields=('name', 'wattage'), name='unique_psu_name_wattage'),
        ),
    ]
