# Generated by Django 5.2.3 on 2025-09-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_alter_psu_name_psu_unique_psu_name_wattage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprice',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IE', 'Ireland'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PT', 'Portugal'), ('RO', 'Romania'), ('SA', 'Saudi Arabia'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=100),
        ),
        migrations.AlterField(
            model_name='coolerprice',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IE', 'Ireland'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PT', 'Portugal'), ('RO', 'Romania'), ('SA', 'Saudi Arabia'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cpuprice',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IE', 'Ireland'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PT', 'Portugal'), ('RO', 'Romania'), ('SA', 'Saudi Arabia'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gpuprice',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IE', 'Ireland'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PT', 'Portugal'), ('RO', 'Romania'), ('SA', 'Saudi Arabia'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=100),
        ),
        migrations.AlterField(
            model_name='psuprice',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IE', 'Ireland'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PT', 'Portugal'), ('RO', 'Romania'), ('SA', 'Saudi Arabia'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ramprice',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IE', 'Ireland'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PT', 'Portugal'), ('RO', 'Romania'), ('SA', 'Saudi Arabia'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=100),
        ),
        migrations.AlterField(
            model_name='storageprice',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CA', 'Canada'), ('CZ', 'Czech Republic'), ('DK', 'Denmark'), ('FI', 'Finland'), ('FR', 'France'), ('DE', 'Germany'), ('HU', 'Hungary'), ('IE', 'Ireland'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('NZ', 'New Zealand'), ('NO', 'Norway'), ('PT', 'Portugal'), ('RO', 'Romania'), ('SA', 'Saudi Arabia'), ('SK', 'Slovakia'), ('ES', 'Spain'), ('SE', 'Sweden'), ('UK', 'United Kingdom'), ('US', 'United States')], max_length=100),
        ),
    ]
