# Generated by Django 5.2.3 on 2025-09-06 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_alter_caseprice_country_alter_coolerprice_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='pcPartPickerId',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
