# Generated by Django 5.2.3 on 2025-09-06 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_alter_cpu_pcpartpickerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseprice',
            name='buyLink',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='coolerprice',
            name='buyLink',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='architecture',
            field=models.CharField(choices=[('ZEN', 'Zen'), ('ZEN+', 'Zen+'), ('ZEN 2', 'Zen 2'), ('ZEN 3', 'Zen 3'), ('ZEN 4', 'Zen 4'), ('ZEN 5', 'Zen 5'), ('COFFEE LAKE REFRESH', 'Coffee Lake Refresh'), ('COMET LAKE', 'Comet Lake'), ('ROCKET LAKE', 'Rocket Lake'), ('ALDER LAKE', 'Alder Lake'), ('RAPTOR LAKE', 'Raptor Lake'), ('RAPTOR LAKE REFRESH', 'Raptor Lake Refresh'), ('ARROW LAKE', 'Arrow Lake')]),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='boostClock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.CharField(choices=[('AMD', 'AMD'), ('INTEL', 'Intel')]),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='coreCount',
            field=models.IntegerField(choices=[(4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12'), (14, '14'), (16, '16'), (18, '18'), (20, '20'), (22, '22'), (24, '24'), (26, '26'), (28, '28'), (30, '30'), (32, '32'), (34, '34'), (36, '36'), (38, '38'), (40, '40')]),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='pcPartPickerId',
            field=models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='series',
            field=models.CharField(choices=[('RYZEN 3', 'Ryzen 3'), ('RYZEN 5', 'Ryzen 5'), ('RYZEN 7', 'Ryzen 7'), ('RYZEN 9', 'Ryzen 9'), ('CORE I3', 'Core i3'), ('CORE I5', 'Core i5'), ('CORE I7', 'Core i7'), ('CORE I9', 'Core i9'), ('CORE ULTRA 5', 'Core Ultra 5'), ('CORE ULTRA 7', 'Core Ultra 7'), ('CORE ULTRA 9', 'Core Ultra 9')]),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(choices=[('AM4', 'AM4'), ('AM5', 'AM5'), ('LGA1151', 'LGA1151'), ('LGA1200', 'LGA1200'), ('LGA1700', 'LGA1700'), ('LGA1851', 'LGA1851')]),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='threadCount',
            field=models.IntegerField(choices=[(4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12'), (14, '14'), (16, '16'), (18, '18'), (20, '20'), (22, '22'), (24, '24'), (26, '26'), (28, '28'), (30, '30'), (32, '32'), (34, '34'), (36, '36'), (38, '38'), (40, '40')]),
        ),
        migrations.AlterField(
            model_name='cpuprice',
            name='buyLink',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gpuprice',
            name='buyLink',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='psuprice',
            name='buyLink',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ramprice',
            name='buyLink',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='storageprice',
            name='buyLink',
            field=models.URLField(max_length=1000),
        ),
    ]
