# Generated by Django 5.2.3 on 2025-07-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
