# Generated by Django 5.2.3 on 2025-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_remove_cpu_buylink_remove_cpu_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='pcPartPickerId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
