# Generated by Django 5.2.3 on 2025-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_storage_rename_amount_ram_size_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cpuprice',
            constraint=models.UniqueConstraint(fields=('CPUId', 'country'), name='unique_cpu_country_price'),
        ),
        migrations.AddConstraint(
            model_name='gpuprice',
            constraint=models.UniqueConstraint(fields=('GPUId', 'country'), name='unique_gpu_country_price'),
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('name', 'size'), name='unique_storage_name_size'),
        ),
        migrations.AddConstraint(
            model_name='storageprice',
            constraint=models.UniqueConstraint(fields=('StorageId', 'country'), name='unique_storage_country_price'),
        ),
    ]
