# Generated by Django 5.2.3 on 2025-08-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_cpuprice_unique_cpu_country_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooler',
            name='width',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpuprice',
            name='buyLink',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpuprice',
            name='buyLink',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storageprice',
            name='buyLink',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PSUPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
                ('PSUId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.psu')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('PSUId', 'country'), name='unique_psu_country_price')],
            },
        ),
    ]
