# Generated by Django 5.2.3 on 2025-08-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_ramprice_cooler_rating_ram_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ram',
            name='unique_ram_name_size',
        ),
        migrations.AddConstraint(
            model_name='ram',
            constraint=models.UniqueConstraint(fields=('name', 'count', 'size'), name='unique_ram_name_count_size'),
        ),
    ]
