# Generated by Django 5.2.3 on 2025-08-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_remove_ram_unique_ram_name_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='depth',
            new_name='length',
        ),
        migrations.AddField(
            model_name='case',
            name='includedPSUWattage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('buyLink', models.URLField(max_length=500)),
                ('CaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.case')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('CaseId', 'country'), name='unique_case_country_price')],
            },
        ),
    ]
